### ISSUE TITLE
Satori Logo

### ISSUE THREAD

**Issue by hpanago** [satori-ng/Project-Requirements#2]
There is also a minor issue, but since this is a rewrite, we need a logo to go with it.

**Comment by operatorequals** [comment]
Totally agreed!
Bear in mind that several projects are named "*Satori*" in some way in the context of Python:
* https://www.satori.com/docs/rtm-sdks/tutorials/python-sdk-quickstart
* https://pypi.python.org/pypi/satori-raspberry/0.0.4

Even a same name project:
* https://pypi.python.org/pypi/satori/0.1.5

Finally, it appears that there is a logo of it in this repo:
* https://bitbucket.org/satoriproject/satori/overview


So, the logo has to be really different.

**Comment by screwdycrow** [comment]
I am attaching in this issue some first ideas, i had for the logo. Taking into consideration the logos that already exists, i tried to come up with some new and unique looking that will embrace the idea behind 
the word Satori. 

The first ideas with the vector monk were mostly inteded as a "badge" logo and i am not sure if they could work as an actuall logo, but i made some versions either way.

I am mainly inclined towards the circular logos. There are some more ideas i would like to work on, that would showcase a bit more the nature of this repo, and i also need to make the "dark background" versons of all the logos. I will get back with those, within this week. 

Here are what i currently have.

![satorioverview](https://user-images.githubusercontent.com/25017675/36476035-5b94c7d8-1705-11e8-9d9a-cdbd6688a0c6.png)
[satori.pdf](https://github.com/satori-ng/Project-Requirements/files/1743678/satori.pdf)

I also liked a lot the ascii character art in the satori, main repo, and i tried to include it a version of it in the logos. Although i was unable to replicate it 100% in affinity designer even by using the same monospace font used on the repo.

**Comment by operatorequals** [comment]
You are fuckin' kidding me now...
 I love your work. 
**Get this man a cookie**

**Comment by screwdycrow** [comment]
@operatorequals that's awesome to hear! Do you like something specifically?  If so tell me which  and i will prepare it for you accordingly. If not i will work on some other ideas i had.

**Comment by operatorequals** [comment]
Hey, as of the last meeting, we'll go with the left-down logo and both left stickers.
Also, your PDF rocks with all that info about your work.

Next meeting you are invited as well - to grab a bunch o' beers with us

**Comment by screwdycrow** [comment]
> Hey, as of the last meeting, we'll go with the left-down logo and both left stickers.
Also, your PDF rocks with all that info about your work.

Thanks!! sorry for the late response, i will have them ready within this weekend and i will attach them here, 
> Next meeting you are invited as well - to grab a bunch o' beers with us

Let the beer flow already :P

**Comment by screwdycrow** [comment]
[SatoriExport.zip](https://github.com/satori-ng/Project-Requirements/files/1822199/SatoriExport.zip)
 I obviously am late again :P... anyways, im attaching the logos you will find badges and logos im their appropriate directory. For each and every design you will find, a small png, a pdf file (good for printing) and an svg file. I believe this is all you will ever need.

**Comment by operatorequals** [comment]
https://github.com/satori-ng/Logos
Finally published and waiting.
Code is getting written as I am posting too.

Thanks for everything dude! Have fun in Erasmus!
